# -*- coding: utf-8 -*-
"""DAY 3 AISHU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heoqcFsP-AuuQ-oPLZCQEtjsYNuL2XFM
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

#Parameters
vocab_size = 1000 #Number of unique words in your vocabulary
embedding_dim = 64 #size of word vector representations
max_length = 100 #Max length of input sequence

#Build the model
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    LSTM(64),
    Dense(1, activation='sigmoid') #use 'softmax' if you have multiple classes
    ])

#Compile the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#prist model summary
model.summary()